name: notify
description: "A Notice App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1  
  file_picker: ^8.0.0
  open_file: ^3.3.2
  path: ^1.9.1
  firebase_core: ^3.5.0
  firebase_messaging: ^15.0.0
  onesignal_flutter: ^5.0.0
  intl: ^0.18.1
  shared_preferences: ^2.5.3
  flutter_gif: ^0.0.4
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  socket_io_client: ^2.0.0
  flutter_local_notifications: ^19.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bell.gif
    - assets/images/bell.png

# 👇 yeh hamesha root level pe rakho
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/bell.png"
  min_sdk_android: 21
