// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACnK_N4Qmh3SN_zKtEwyZAc0anhotI5X4',
    appId: '1:680326695326:web:d224b125d84ef702baee8f',
    messagingSenderId: '680326695326',
    projectId: 'notice-app-notification',
    authDomain: 'notice-app-notification.firebaseapp.com',
    storageBucket: 'notice-app-notification.firebasestorage.app',
    measurementId: 'G-VL95TCTJTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbsUnit_N2uXhkry8a1cmHTQ-1uN7fvm8',
    appId: '1:680326695326:android:6a2543c72789ed65baee8f',
    messagingSenderId: '680326695326',
    projectId: 'notice-app-notification',
    storageBucket: 'notice-app-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuuNF7XepCFlYI6tANYkTgeqonKuSLYc0',
    appId: '1:680326695326:ios:1674f35895cc4f01baee8f',
    messagingSenderId: '680326695326',
    projectId: 'notice-app-notification',
    storageBucket: 'notice-app-notification.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuuNF7XepCFlYI6tANYkTgeqonKuSLYc0',
    appId: '1:680326695326:ios:1674f35895cc4f01baee8f',
    messagingSenderId: '680326695326',
    projectId: 'notice-app-notification',
    storageBucket: 'notice-app-notification.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACnK_N4Qmh3SN_zKtEwyZAc0anhotI5X4',
    appId: '1:680326695326:web:a357cd8e542d1f45baee8f',
    messagingSenderId: '680326695326',
    projectId: 'notice-app-notification',
    authDomain: 'notice-app-notification.firebaseapp.com',
    storageBucket: 'notice-app-notification.firebasestorage.app',
    measurementId: 'G-2FDRZ6M1FV',
  );
}
